# config
name: portifolio
url: "cesarbruschetta.github.io"
baseurl: "" 

# Profile information
author: "Cesar Augusto"
title: "Desenvolvedor | "

# Meta Tag
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

domain: "cesarbruschetta.com.br"

# Social
twitter: cesarbruschetta
github: cesarbruschetta
gitlab: cesarbruschetta
linkedin: cesarbruschetta
slack: cesarbruschetta/shared_invite/enQtODg0OTU1NzI5NTIxLTdjNDBiZDkzZDQ5ZmVjYTFkNTc1YTcyODcwYzZhMDRhM2JlZWM0NGYwMmUyYjNiYzE1ZWVlNGM4MDA2MmExMWQ
telegram: cesarbruschetta
stackOverflow: 10342534

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README*

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  style: compressed