# Profile information
name: portifolio
title: Porfifolio - Cesar Bruschetta
email: #your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" 
url: "cesarbruschetta.github.io"

# Social
twitter: cesarbruschetta
github: cesarbruschetta

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README*

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  style:              compressed